# Generated by Django 4.2.5 on 2023-10-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload_app', '0002_create_builtin_account_tiers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiringlink',
            name='expiration_date',
            field=models.DateTimeField(null=True),
        ),
    ]
