# Generated by Django 4.2.5 on 2023-12-09 19:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload_app', '0003_alter_expiringlink_expiration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounttier',
            name='can_generate_expiring_link',
        ),
        migrations.RemoveField(
            model_name='accounttier',
            name='has_original_link',
        ),
        migrations.RemoveField(
            model_name='accounttier',
            name='is_builtin',
        ),
        migrations.RemoveField(
            model_name='accounttier',
            name='thumbnail_sizes',
        ),
        migrations.RemoveField(
            model_name='expiringlink',
            name='expiry_seconds',
        ),
        migrations.RemoveField(
            model_name='image',
            name='original_link',
        ),
        migrations.RemoveField(
            model_name='image',
            name='thumbnails',
        ),
        migrations.AlterField(
            model_name='expiringlink',
            name='expiration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
