# Generated by Django 4.2.5 on 2024-03-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload_app', '0004_remove_accounttier_can_generate_expiring_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
