# Generated by Django 4.2.5 on 2024-03-10 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload_app', '0006_alter_customuser_account_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_tier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='image_upload_app.accounttier'),
        ),
    ]
