# Generated by Django 4.2.5 on 2024-03-10 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload_app', '0008_alter_image_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='token',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='account_tier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='image_upload_app.accounttier'),
        ),
        migrations.AlterField(
            model_name='image',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
