# Generated by Django 4.2.5 on 2024-03-23 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload_app', '0011_alter_expiringlink_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='uploaded_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
