# Generated by Django 4.2.5 on 2024-03-23 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload_app', '0012_image_uploaded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='uploaded_by',
        ),
    ]
